version: '3.7'
services:
  app:
    build:
      context: .
    expose:
      - '8000'
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
